source ~/.config/shell/exports
source ~/.config/shell/aliases
source ~/.config/shell/functions
source ~/.config/shell/plugins

HISTSIZE=10000
SAVEHIST=20000
HISTFILE=~/.zsh_history

setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt APPEND_HISTORY
setopt SHARE_HISTORY
setopt HIST_REDUCE_BLANKS
setopt HIST_VERIFY
setopt HIST_FIND_NO_DUPS

setopt AUTO_CD
setopt EXTENDED_GLOB
setopt AUTO_PUSHD
setopt PUSHD_IGNORE_DUPS
setopt NO_HUP
setopt NO_CHECK_JOBS

zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
zstyle ':completion:*' menu select

if (( $+commands[starship] )); then
    eval "$(starship init zsh)"
else
    PROMPT='%F{green}%n@%m%f:%F{blue}%~%f%# '
fi

(( $+commands[fastfetch] )) && fastfetch

[[ -f ~/.config/shell/local ]] && source ~/.config/shell/local

eval "$(zoxide init --cmd j zsh)"
export PATH="$HOME/.local/share/mise/shims:$PATH"

export SUDO_EDITOR=nvim

bindkey -v

zle-keymap-select() {
    if [[ ${KEYMAP} == vicmd ]] || [[ $1 = 'block' ]]; then
        echo -ne '\e[1 q'
    elif [[ ${KEYMAP} == main ]] || [[ ${KEYMAP} == viins ]] || [[ $1 = 'beam' ]]; then
        echo -ne '\e[5 q'
    fi
}
zle -N zle-keymap-select

zle-line-init() {
    echo -ne "\e[5 q"
}
zle -N zle-line-init

source $ZSH_CUSTOM/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh 2>/dev/null &!
