format = """
[](fg:#df8e1d)$username[](bg:#1e66f5 fg:#df8e1d)$directory[](fg:#1e66f5 bg:#d20f39)$git_branch$git_status[](fg:#d20f39 bg:#ea76cb)$time[ ](fg:#ea76cb)"""

[username]
show_always = true
style_user = "bg:#df8e1d"
style_root = "bg:#df8e1d"
format = '[$user ]($style)'
disabled = false

[directory]
style = "bg:#1e66f5"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#d20f39"
format = '[[ $symbol $branch ](bg:#d20f39)]($style)'

[git_status]
style = "bg:#d20f39"
format = '[[($all_status$ahead_behind )](bg:#d20f39)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#ea76cb"
format = '[[  $time ](bg:#ea76cb)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:#40a02b)'
error_symbol = '[](bold fg:#d20f39)'
vimcmd_symbol = '[](bold fg:#40a02b)'
vimcmd_replace_one_symbol = '[](bold fg:)'
vimcmd_replace_symbol = '[](bold fg:)'
vimcmd_visual_symbol = '[](bold fg:#df8e1d)'
