format = """
[](fg:#eed49f)$username[](bg:#8aadf4 fg:#eed49f)$directory[](fg:#8aadf4 bg:#ed8796)$git_branch$git_status[](fg:#ed8796 bg:#f5bde6)$time[ ](fg:#f5bde6)"""

[username]
show_always = true
style_user = "bg:#eed49f"
style_root = "bg:#eed49f"
format = '[$user ](bg:#eed49f fg:#494d64)'
disabled = false

[directory]
style = "bg:#8aadf4"
format = "[ $path ](bg:#8aadf4 fg:#494d64)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#ed8796"
format = '[[ $symbol $branch ](bg:#ed8796 fg:#494d64)]($style)'

[git_status]
style = "bg:#ed8796"
format = '[[($all_status$ahead_behind )](bg:#ed8796 fg:#494d64)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#f5bde6"
format = '[[  $time ](bg:#f5bde6 fg:#494d64)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:#a6da95)'
error_symbol = '[](bold fg:#ed8796)'
vimcmd_symbol = '[](bold fg:#a6da95)'
vimcmd_replace_one_symbol = '[](bold fg:)'
vimcmd_replace_symbol = '[](bold fg:)'
vimcmd_visual_symbol = '[](bold fg:#eed49f)'
