format = """
[](fg:0xd8a657)$username[](bg:0x7daea3 fg:0xd8a657)$directory[](fg:0x7daea3 bg:0xea6962)$git_branch$git_status[](fg:0xea6962 bg:0xd3869b)$time[ ](fg:0xd3869b)"""

[username]
show_always = true
style_user = "bg:0xd8a657"
style_root = "bg:0xd8a657"
format = '[$user ]($style)'
disabled = false

[directory]
style = "bg:0x7daea3"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:0xea6962"
format = '[[ $symbol $branch ](bg:0xea6962)]($style)'

[git_status]
style = "bg:0xea6962"
format = '[[($all_status$ahead_behind )](bg:0xea6962)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:0xd3869b"
format = '[[  $time ](bg:0xd3869b)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:0xa9b665)'
error_symbol = '[](bold fg:0xea6962)'
vimcmd_symbol = '[](bold fg:0xa9b665)'
vimcmd_replace_one_symbol = '[](bold fg:)'
vimcmd_replace_symbol = '[](bold fg:)'
vimcmd_visual_symbol = '[](bold fg:0xd8a657)'
