format = """
[](fg:#b91c1c)$username[](bg:#e68e0d fg:#b91c1c)$directory[](fg:#e68e0d bg:#D35F5F)$git_branch$git_status[](fg:#D35F5F bg:#D35F5F)$time[ ](fg:#D35F5F)"""

[username]
show_always = true
style_user = "bg:#b91c1c"
style_root = "bg:#b91c1c"
format = '[$user ](bg:#b91c1c fg:#333333)'
disabled = false

[directory]
style = "bg:#e68e0d"
format = "[ $path ](bg:#e68e0d fg:#333333)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#D35F5F"
format = '[[ $symbol $branch ](bg:#D35F5F fg:#333333)]($style)'

[git_status]
style = "bg:#D35F5F"
format = '[[($all_status$ahead_behind )](bg:#D35F5F fg:#333333)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#D35F5F"
format = '[[  $time ](bg:#D35F5F fg:#333333)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:#FFC107)'
error_symbol = '[](bold fg:#D35F5F)'
vimcmd_symbol = '[](bold fg:#FFC107)'
vimcmd_replace_one_symbol = '[](bold fg:)'
vimcmd_replace_symbol = '[](bold fg:)'
vimcmd_visual_symbol = '[](bold fg:#b91c1c)'
