format = """
[](fg:#ebcb8b)$username[](bg:#81a1c1 fg:#ebcb8b)$directory[](fg:#81a1c1 bg:#bf616a)$git_branch$git_status[](fg:#bf616a bg:#b48ead)$time[ ](fg:#b48ead)"""

[username]
show_always = true
style_user = "bg:#ebcb8b"
style_root = "bg:#ebcb8b"
format = '[$user ](bg:#ebcb8b fg:#3b4252)'
disabled = false

[directory]
style = "bg:#81a1c1"
format = "[ $path ](bg:#81a1c1 fg:#3b4252)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#bf616a"
format = '[[ $symbol $branch ](bg:#bf616a fg:#3b4252)]($style)'

[git_status]
style = "bg:#bf616a"
format = '[[($all_status$ahead_behind )](bg:#bf616a fg:#3b4252)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#b48ead"
format = '[[  $time ](bg:#b48ead fg:#3b4252)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:#a3be8c)'
error_symbol = '[](bold fg:#bf616a)'
vimcmd_symbol = '[](bold fg:#a3be8c)'
vimcmd_replace_one_symbol = '[](bold fg:)'
vimcmd_replace_symbol = '[](bold fg:)'
vimcmd_visual_symbol = '[](bold fg:#ebcb8b)'
