format = """
[](fg:#f9cc6c)$username[](bg:#f38d70 fg:#f9cc6c)$directory[](fg:#f38d70 bg:#fd6883)$git_branch$git_status[](fg:#fd6883 bg:#a8a9eb)$time[ ](fg:#a8a9eb)"""

[username]
show_always = true
style_user = "bg:#f9cc6c"
style_root = "bg:#f9cc6c"
format = '[$user ](bg:#f9cc6c fg:#2c2525)'
disabled = false

[directory]
style = "bg:#f38d70"
format = "[ $path ](bg:#f38d70 fg:#2c2525)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#fd6883"
format = '[[ $symbol $branch ](bg:#fd6883 fg:#2c2525)]($style)'

[git_status]
style = "bg:#fd6883"
format = '[[($all_status$ahead_behind )](bg:#fd6883 fg:#2c2525)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#a8a9eb"
format = '[[  $time ](bg:#a8a9eb fg:#2c2525)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:#adda78)'
error_symbol = '[](bold fg:#fd6883)'
vimcmd_symbol = '[](bold fg:#adda78)'
vimcmd_replace_one_symbol = '[](bold fg:)'
vimcmd_replace_symbol = '[](bold fg:)'
vimcmd_visual_symbol = '[](bold fg:#f9cc6c)'
