accent = "#e07b39"
cursor = "#e07b39"
foreground = "#ddd0bc"
background = "#0e0e13"
selection_foreground = "#0e0e13"
selection_background = "#e07b39"

color0 = "#1a1a23"
color1 = "#c75454"
color2 = "#78a878"
color3 = "#c89f4a"
color4 = "#4a7aaa"
color5 = "#9a6090"
color6 = "#4a9898"
color7 = "#c0b8a8"
color8 = "#2a2a38"
color9 = "#e06060"
color10 = "#90c090"
color11 = "#e0b855"
color12 = "#5a90c8"
color13 = "#b07aaa"
color14 = "#5ab0b0"
color15 = "#e0d8c8"
