[bar]
background-alpha = 0.5
islands = true
margin = 16
margin-bottom = 0
island-padding-x = 16
island-padding-y = 2
island-radius = 32

[menu]
background-alpha = 0.6
scrim-alpha = 0.0

[popups]
background-alpha = 0.9

[font]
base-size = 13
