windowrulev2 = tile,class:^(steam)$
windowrulev2 = stayfocused, title:^()$,class:^(steam)$
windowrulev2 = minsize 1 1, title:^()$,class:^(steam)$
# windowrulev2 = float, title:^()$,class:^(steam)$
windowrulev2 = idleinhibit fullscreen, class:.*

# Unity Hub
windowrulev2 = float, class:^(unityhub)$
windowrulev2 = center, class:^(unityhub)$
windowrulev2 = size 1200 800, class:^(unityhub)$

# Unity Editor popups float
windowrulev2 = float, class:^(Unity)$, title:^(Unity.*Hub)$
windowrulev2 = float, class:^(Unity)$, title:^(Unity License.*)$
windowrulev2 = float, class:^(Unity)$, title:^(Importing.*)$
windowrulev2 = center, class:^(Unity)$, title:^(Unity.*Hub)$

# stop tooltip/dropdown focus steal
windowrulev2 = nofocus, class:^(Unity)$, title:^$
windowrulev2 = noinitialfocus, class:^(Unity)$, title:^(.*dropdown.*)$

# kill transparency/blur glitches
windowrulev2 = opaque, class:^(Unity)$
windowrulev2 = noblur, class:^(Unity)$
windowrulev2 = noshadow, class:^(Unity)$

# fix zero-size splash
windowrulev2 = minsize 1 1, class:^(Unity)$
